# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mmcif_data_holder <- function(covs_trajectory, d_covs_trajectory, covs_risk, has_finite_trajectory_prob, cause, n_causes, pair_indices, singletons) {
    .Call(`_mmcif_mmcif_data_holder_to_R`, covs_trajectory, d_covs_trajectory, covs_risk, has_finite_trajectory_prob, cause, n_causes, pair_indices, singletons)
}

mmcif_logLik <- function(data_ptr, par, ghq_data, n_threads) {
    .Call(`_mmcif_mmcif_logLik_to_R`, data_ptr, par, ghq_data, n_threads)
}

